# Streamlit Secrets Configuration
# This file shows the format for secrets.toml
# DO NOT commit secrets.toml - it contains API keys!
# Copy this file to secrets.toml and add your actual API key

# Kimi/Moonshot AI API Key (Primary LLM Provider)
# Get from: https://platform.moonshot.cn/
MOONSHOT_API_KEY = "sk-xxxxxxxxxxxxx"

# Optional: OpenRouter API Key (Fallback Provider)
# Get from: https://openrouter.ai/keys
# OPENROUTER_API_KEY = "sk-or-xxxxxxxxxxxxx"

# Optional: Additional configuration
# LOG_LEVEL = "INFO"
