# Streamlit Secrets Configuration
# This file shows the format for secrets.toml
# DO NOT commit secrets.toml - it contains API keys!
# Copy this file to secrets.toml and add your actual API key

# Anthropic Claude API Key
# Get from: https://console.anthropic.com/account/keys
ANTHROPIC_API_KEY = "sk-ant-xxxxxxxxxxxxx"

# Optional: Additional configuration
# LOG_LEVEL = "INFO"
